# Cian McSharry Daly
# Student ID : 43857
# Stage 1 - simpleshell project.

# Construct target file with file dependency objects 
#	-Wall - Enable all warning messages.
simpleshell: src/simpleshell.c src/helperfunctions.c src/functions.c src/utility.h
	gcc -Wall src/simpleshell.c src/helperfunctions.c src/functions.c -o bin/simpleshell

clean:
	rm -f bin/simpleshell
